### ISSUE TITLE
How to compile correctly files DNG in Windows 10 with the GCC?

### ISSUE THREAD

**Issue by Jamaika1** [yanburman/dng_sdk#1]
Hi yanburman
I am sending source
https://www.sendspace.com/file/m3i7s9
Regards

**Comment by yanburman** [comment]
could you elaborate a bit more on what you are trying to do and what is the problem?
I am using cmake (projects/cmake/CMakeLists.txt) to compile dng_sdk for different platform (currently works on Linux, Windows 7/10 32/64 bit and MacOS). I guess you can adjust the cmake to allow gcc on windows, but it may be a world of pain doing that for XMP SDK cmake

**Comment by Jamaika1** [comment]
My problem
_dng_validate.exe yuv8bit.jpg RGB24.dng
*** Error: Unknown error ***
*** Error: Unable to allocate memory ***
*** Exception thrown in main routine_

**Comment by Jamaika1** [comment]
dng_validate.exe yuv8bit.jpg RGB24.dng
_*** Error: Unknown error ***
*** Error: Unable to allocate memory ***
*** Exception thrown in main routine_
