### ISSUE TITLE
How to compile correctly files DNG in Windows 10 with the GCC?

### ISSUE THREAD

**Issue by Jamaika1** [yanburman/dng_sdk#2]
Hi yanburman
I am sending source
https://www.sendspace.com/file/m3i7s9
Regards

_could you elaborate a bit more on what you are trying to do and what is the problem?
 I am using cmake (projects/cmake/CMakeLists.txt) to compile dng_sdk for different platform (currently works on Linux, Windows 7/10 32/64 bit and MacOS). I guess you can adjust the cmake to allow gcc on windows, but it may be a world of pain doing that for XMP SDK cmake_

dng_validate.exe yuv8bit.jpg RGB24.dng
*** Error: Unknown error ***
 *** Error: Unable to allocate memory ***
 *** Exception thrown in main routine

**Comment by yanburman** [comment]
I don't have gcc on windows. on Linux it compiles ok with gcc and on windows with MSVC. Also, there are number of problems with your issue report:
1) You did not explain what you are trying to do
2) The sources you sent do not match what is in this repository (perhaps it is because you opened the same issue to 5 differrent repositories)
3) The sources you provided are strange, since .o files are not recognized as anything valid and dng_validate.exe is of zero (0) size

I would be glad to review a pull request from you assuming you find the issue

**Comment by Jamaika1** [comment]
Ad 1. I wanted to convert the image JPEG 4K to AdobeDNG,
Ad 2. I know that in resporitorium are changes, but in your resporitorium also doesn't want to start. I also found some version of the Windows. 
https://github.com/ttyangf/dng_sdk
I didn't succeed to correctly produce file _dng_validate.exe_. :(
Ad 3. I lost a lot of time, is subjected to. I see it is that the program is intended function under Windows.

_#define qLinux 0
## **#define qWinOS 1**
#define qMacOS 0

#define qDNGThreadSafe 1
#define qDNGValidateTarget 1
#define qDNGXMPDocOps 0
#define UNIX_ENV 0_

**Comment by yanburman** [comment]
dng_validate is not intended for converting jpeg to dng as far as I know.
When I run a properly compiled dng_validate, I get the following:

dng_validate -dng ttt.dng 2016_0616_165929_002.JPG
Validating "2016_0616_165929_002.JPG"...
*** Error: Unknown byte order ***
*** Error: File format is invalid ***

You may want to read this:
https://forums.adobe.com/thread/983320
https://forums.adobe.com/thread/398363

**Comment by Jamaika1** [comment]
Thanks for the link. In that case, I don't understand why has this software a built-in read and save libjpeg? I use libjpeg 9.2. Brought me here advertising and miserliness because I didn't want to spend on software.

Not to exalt. It is advertising for two years in the network that was created lossless jpeg with functions RGB or YCoCg 8/10/12bit based on AdobeDNG. I believe that these threads are old. FFmpeg decode have these pictures JPEG.
http://thndl.com/how-dng-compresses-raw-data-with-lossless-jpeg92.html

**Comment by yanburman** [comment]
libjpeg is used for thumbnail generation in dng as far as I saw.
